### ISSUE TITLE
Error while using pip

### ISSUE THREAD

**Issue by gauravparashar** [kkrusere/NHANES-pyTOOL-API#1]
When I ran it on Ubuntu 20.04 it gave me this error
ERROR: Could not find a version that satisfies the requirement nhanes_pytool_api (from versions: none)
ERROR: No matching distribution found for nhanes_pytool_api

Can you please tell me what is the workaround for this problem?

**Comment by kkrusere** [comment]
Hello [@gauravparashar](https://github.com/gauravparashar),

Thank you for reaching out. The installation issue has been resolved. You can now install the package using either of the following commands:

To install using the name "nhanes_pytool_api":
`pip install nhanes_pytool_api`
Or, 
`pip install nhanes-pytool-api`

Either of these commands should work for you. If you encounter any further issues or have questions, please feel free to reach out. Thank you for your patience!

Best regards,

Kuzi Rusere

**Comment by gauravparashar** [comment]
Ok thank you
